# Generated by Django 4.2.5 on 2023-10-05 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, verbose_name='Товар')),
                ('group', models.CharField(max_length=100, verbose_name='Группа')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('subcategory', models.CharField(max_length=100, verbose_name='Подкатегория')),
                ('uom', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(db_index=True, max_length=100, verbose_name='Магазин')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Город')),
                ('division', models.CharField(db_index=True, max_length=100, verbose_name='Дивизион')),
                ('type_format', models.PositiveIntegerField(db_index=True, verbose_name='Формат магазина')),
                ('loc', models.PositiveIntegerField(db_index=True, verbose_name='Локация магазина')),
                ('size', models.PositiveIntegerField(db_index=True, verbose_name='Размер магазина')),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Торговый комплекс',
                'verbose_name_plural': 'Тороговые комплексы',
                'ordering': ('store',),
            },
        ),
        migrations.CreateModel(
            name='SalesSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categories')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shops')),
            ],
            options={
                'verbose_name': 'прогонзыы',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('sales_type', models.IntegerField()),
                ('sales_units', models.IntegerField()),
                ('sales_units_promo', models.IntegerField(blank=True, null=True)),
                ('sales_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_run_promo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categories')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shops')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информации',
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('forecast', models.JSONField()),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shops')),
            ],
            options={
                'verbose_name': 'Прогноз',
                'verbose_name_plural': 'Прогнозы',
            },
        ),
    ]
