# Generated by Django 4.2.5 on 2023-10-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salessub',
            options={'verbose_name': 'прогонзы'},
        ),
    ]
