version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: ivanmatveev/lenta_backend:latest
    build:
      context: ./backend/
      dockerfile: Dockerfile
    restart: always
    # volumes:
    #   - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  # frontend:
  #   image: ivanmatveev/lenta_frontend:latest
  #   build:
  #     context: ./frontend/
  #     dockerfile: Dockerfile
  #   # volumes:
  #   #   - ../frontend/:/app/result_build/
  #   depends_on:
  #     - backend

  data_science:
    image: ivanmatveev/lenta_data_science:latest
    build:
      context: ./backend/
      dockerfile: Dockerfile
    depends_on:
      - backend

volumes:
  db_value:
